# Generated by Django 4.2 on 2024-01-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Текущая температура')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Давление в мм рт.ст.')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Скорость ветра')),
                ('request_timestamp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
