# Generated by Django 4.2 on 2024-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='request_timestamp',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Временная метка'),
        ),
    ]
