# Generated by Django 4.2 on 2024-01-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_weather', '0002_alter_weather_request_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='request_timestamp',
        ),
    ]
